name: Deploy Frontend to LXC

on:
  push:
    branches:
      - merx

env:
  BASTION_HOST: ${{ secrets.BASTION_HOST }}
  BASTION_PORT: ${{ secrets.BASTION_PORT }}
  BASTION_USER: ${{ secrets.BASTION_USER }}

  INTERNAL_HOST: ${{ secrets.INTERNAL_HOST }}
  INTERNAL_PORT: ${{ secrets.INTERNAL_PORT }}
  INTERNAL_USER: ${{ secrets.INTERNAL_USER }}

  # /var/www/html/pruebas/
  REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
  LOCAL_TUNNEL_PORT: 2022

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build React app
        env:
          CI: false
        run: npm run build

      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      - name: Abrir túnel SSH al contenedor vía bastion
        env:
          SSHPASS: ${{ secrets.BASTION_PASSWORD }}
        run: |
          setsid sshpass -e ssh -N -v \
            -p "$BASTION_PORT" \
            -L "$LOCAL_TUNNEL_PORT:$INTERNAL_HOST:$INTERNAL_PORT" \
            -o StrictHostKeyChecking=accept-new \
            -o ExitOnForwardFailure=yes \
            -o ServerAliveInterval=30 \
            "$BASTION_USER@$BASTION_HOST" > tunnel.log 2>&1 &

          if timeout 15 bash -c "until nc -z localhost $LOCAL_TUNNEL_PORT; do sleep 0.2; done"; then
            echo "Tunel accesible en localhost:$LOCAL_TUNNEL_PORT"
          else
            echo "ERROR: el tunel no quedo accesible en localhost:$LOCAL_TUNNEL_PORT"
            echo "----- LOG DEL TUNEL SSH -----"
            cat tunnel.log
            echo "-----------------------------"
            exit 1
          fi

      - name: Copiar build/ al servidor (rsync vía túnel)
        env:
          SSHPASS: ${{ secrets.INTERNAL_PASSWORD }}
        run: |
          sshpass -e rsync -rlzvc --delete \
            --no-perms --no-owner --no-group --no-times --omit-dir-times \
            -e "ssh -p $LOCAL_TUNNEL_PORT -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null" \
            ./build/ "$INTERNAL_USER@localhost:$REMOTE_PATH"

      - name: Cerrar túnel SSH
        if: always()
        run: |
          pkill -f "$LOCAL_TUNNEL_PORT:$INTERNAL_HOST:$INTERNAL_PORT" || true
